"""add composite indexes

Revision ID: cc976b51bc94
Revises: dafc74c801d7
Create Date: 2026-08-31 14:57:57.222908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc976b51bc94'
down_revision: Union[str, Sequence[str], None] = 'dafc74c801d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_email_log_pending', 'email_log', ['opened_at', 'alert_acked', 'reminder_done', 'sent_at'], unique=False)
    op.create_index('idx_received_mail_pending', 'received_mail_log', ['is_seen', 'supervisor_acked', 'reminder_done', 'received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_received_mail_pending', table_name='received_mail_log')
    op.drop_index('idx_email_log_pending', table_name='email_log')
    # ### end Alembic commands ###
