"""index 

Revision ID: d6855d56a71d
Revises: 3ea076d2a692
Create Date: 2026-08-12 02:15:04.507825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6855d56a71d'
down_revision: Union[str, Sequence[str], None] = '3ea076d2a692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


"""index 

Revision ID: d6855d56a71d
Revises: 3ea076d2a692
Create Date: 2026-08-12 02:15:04.507825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6855d56a71d'
down_revision: Union[str, Sequence[str], None] = '3ea076d2a692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_email_log_opened_at'), 'email_log', ['opened_at'], unique=False)
    op.create_index(op.f('ix_email_log_sender_email'), 'email_log', ['sender_email'], unique=False)
    op.create_index(op.f('ix_email_log_sent_at'), 'email_log', ['sent_at'], unique=False)
    op.drop_column('email_log', 'direction')
    op.drop_column('imap_accounts', 'uid_validity')
    op.drop_index(op.f('ix_received_mail_log_account_uid_validity'), table_name='received_mail_log')
    op.create_index(op.f('ix_received_mail_log_imap_account_id'), 'received_mail_log', ['imap_account_id'], unique=False)
    op.create_index(op.f('ix_received_mail_log_received_at'), 'received_mail_log', ['received_at'], unique=False)
    op.create_index(op.f('ix_received_mail_log_sender_email'), 'received_mail_log', ['sender_email'], unique=False)
    op.drop_column('received_mail_log', 'uid_validity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('received_mail_log', sa.Column('uid_validity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_received_mail_log_sender_email'), table_name='received_mail_log')
    op.drop_index(op.f('ix_received_mail_log_received_at'), table_name='received_mail_log')
    op.drop_index(op.f('ix_received_mail_log_imap_account_id'), table_name='received_mail_log')
    op.create_index(op.f('ix_received_mail_log_account_uid_validity'), 'received_mail_log', ['imap_account_id', 'message_uid', 'uid_validity'], unique=False)
    op.add_column('imap_accounts', sa.Column('uid_validity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('email_log', sa.Column('direction', sa.VARCHAR(length=10), server_default=sa.text("'sent'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_email_log_sent_at'), table_name='email_log')
    op.drop_index(op.f('ix_email_log_sender_email'), table_name='email_log')
    op.drop_index(op.f('ix_email_log_opened_at'), table_name='email_log')
    # ### end Alembic commands ###

