"""add monitoring_started_at to app_users

Revision ID: dafc74c801d7
Revises: 0132a12d2d87
Create Date: 2026-08-28 13:06:57.361711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dafc74c801d7'
down_revision: Union[str, Sequence[str], None] = '0132a12d2d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('monitoring_started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_users', 'monitoring_started_at')
    # ### end Alembic commands ###
